var path404 = document.currentScript.src.replace(/\/[^\/]*$/, "/");
var data = [{
    "name": "洪水",
    id: "flood01",
    p: 1,
    expires: "2030-12-31",
    "pc": "<img ondragstart=\"return false\" alt=\"404！您访问的页面可能被台风吹跑了\" style=\"margin-left:calc(50% - 800px);\" src=\"" + path404 + "img/flood_pc.jpg\" width=\"1600\"><a href=\"http://www.cneb.gov.cn/2021/02/26/VIDE1614329850710962.shtml\" style=\"position:absolute;top:860px;left:calc(50% - 80px);width:160px;height:50px;\"></a><a href=\"img/floodQR.jpg\" style=\"color:white;text-decoration: none;font-size: 25px;position:absolute;right:max(calc(50% - 770px),20px);top:765px\"><img src=\"" + path404 + "img/floodQR.jpg\" width=\"200px\"><div>扫码帮助灾区孩子</div></a>",
    "mobile": "<img ondragstart=\"return false\" alt=\"404！您访问的页面可能被台风吹跑了\" src=\"" + path404 + "img/flood_mobile.jpg\" style=\"width:100vw\"><a href=\"http://www.cneb.gov.cn/2021/02/26/VIDE1614329850710962.shtml\" style=\"position:absolute;top:184vw;left:40vw;width:25vw;height:5vw\"></a><a href=\"https://ssl.gongyi.qq.com/m/weixin/yqj.html?gt=xqcyq#/yqj/detail?id=237342&amp;did=1201424501202111106700002057\" style=\"color:white;text-decoration: none;font-size: 3vw;position:relative;display:block;margin-top:-32vw;padding-left:1vw\"><img src=\"" + path404 + "img/floodQR.jpg\" style=\"width:25vw\"><div>扫码帮助灾区孩子</div></a>"
}, {
    "name": "汽车",
    id: "car01",
    p: 1,
    expires: "2030-12-31",
    "pc": "<img ondragstart=\"return false\" alt=\"404！您访问的页面可能被台风吹跑了\" style=\"margin-left:calc(50% - 800px);\" src=\"" + path404 + "img/car.jpg\" width=1600><a href=\"http://www.cneb.gov.cn/2021/02/19/VIDE1613723680613558.shtml\" style=\"position:absolute;top:860px;left:calc(50% - 80px);width:160px;height:50px;\"></a><a href=\"https://wj.qq.com/s2/9163450/732e/\" style=\"color:white;font-size:20px;text-decoration:none;position:absolute;top:950px;left:calc(50% - 50px);\" >我要投稿 ></a>",
    "mobile": "<img  ondragstart=\"return false\"alt=\"404！您访问的页面可能被台风吹跑了\" src=\"" + path404 + "img/car_mobile.jpg\" style=\"width:100vw\"><a href=\"http://www.cneb.gov.cn/2021/02/19/VIDE1613723680613558.shtml\" style=\"position:absolute;top:184vw;left:40vw;width:25vw;height:5vw;\"></a><a href=\"https://wj.qq.com/s2/9163450/732e/\" style=\"color:white;font-size:3.5vw;text-decoration:none;position:absolute;top:200vw;left:42vw;\" >我要投稿 ></a>"
}, {
    "name": "绿色找回",
    id: "greenback001",
    p: 1,
    expires: "2030-12-31",
    "pc": "<img alt=\"404！您访问的页面可能被风吹跑了\" style=\"margin-left:calc(50% - 800px);\" src=\"" + path404 + "img/greenback.png\" width=1600px /><a href=\"https://wj.qq.com/s2/9163450/732e/\" style=\"color:black;font-size:20px;text-decoration:none;position:absolute;top:1000px;left:calc(50% - 43px);\" >我要 <font color=green> 投稿 ></font></a>",
    "mobile": "<img alt=\"404！您访问的页面可能被风吹跑了\" src=\"" + path404 + "img/greenback_mobile.png\" width=100%><a href=\"https://wj.qq.com/s2/9163450/732e/\" style=\"color:black;font-size:3.5vw;text-decoration:none;position:absolute;top:165vw;left:42vw;\" >我要 <font color=green> 投稿 ></font></a>"
}, {
    "name": "绿色找回2",
    id: "greenback002",
    p: 1,
    expires: "2030-12-31",
    "pc": "<img alt=\"404！您访问的页面可能被风吹跑了\" style=\"margin-left:calc(50% - 800px);\" src=\"" + path404 + "img/greenback2.jpg\" width=1600px /><a href=\"https://wj.qq.com/s2/9163450/732e/\" style=\"color:black;font-size:20px;text-decoration:none;position:absolute;top:910px;left:calc(50% - 51px);\" >我要 <font color=green> 投稿 ></font></a>",
    "mobile": "<img alt=\"404！您访问的页面可能被风吹跑了\" src=\"" + path404 + "img/greenback2_mobile.jpg\" width=100%><a href=\"https://wj.qq.com/s2/9163450/732e/\" style=\"color:black;font-size:3.5vw;text-decoration:none;position:absolute;top:175vw;left:42vw;\" >我要 <font color=green> 投稿 ></font></a>"
}, {
    "name": "视障咖啡师",
    id: "barista001",
    p: 0,
    expires: "2022-11-30",
    "pc": "<div style=\"position:relative;\"><img alt=\"404！您要访问的页面不见了！\" src=\"" + path404 + "img/coffee-1600.jpg\" style=\"left:50%;width:1600px;margin-left:calc(50% - 800px);filter: filter:saturate(200%);\"><div style=\"position:absolute;top:0;width:100%;text-align:center;color:white;font-size:28px;\"><div style=\"display:inline-block;width:98vw;max-width:1600px;height:calc(100vh - 300px);max-height:590px;\"><div style=\"font-size:128px;font-weight: 900;\">404</div>您访问的页面已经迷失<br>在寒冷的黑夜里<br>不过您还可以和腾讯志愿者一起<br><i><b style=\"font-size:1.2em\">为黑暗中的咖啡师送去一份温暖</b></i></div><div style=\"width:98vw;max-width:1600px;text-align:right;margin:0px;padding-left:calc(48% - 800px);\"><ranking style=\"display:inline-block;padding:10px;width:240px;\"></ranking><a href=\"" + path404 + "img/coffeeQR.jpg\"><img src=\"" + path404 + "img/coffeeQR.jpg\" alt=\"点击进入支持页面\" style=\"width:230px;\"></a><br>扫码送上一份支持</div></div></div>",
    "mobile": "<center style=\"background-color:black;font-size:4vw;color:#111111;height: 100vh;min-height: 150vw;\"><img alt=\"404！您要访问的页面走丢了！\" src=\"" + path404 + "img/coffee-960.jpg\" style=\"width:95vw;height:90vw;filter:brightness(80%)\"><div style=\"position:absolute;top:0;color:white;text-align: center;width:100%\"><div style=\"font-size:20vw;font-weight: 900;\">404</div>您访问的页面已经迷失在黑夜里<br>不过您还可以和腾讯志愿者一起<br><i><b style=\"font-size:1.2em\">为黑暗中的咖啡师送去一份温暖</b></i></div><div style=\"background-image: linear-gradient(to bottom, rgba(0,0,0,0), rgba(0,0,0,1));position:relative;top:-20vw;height:20vw;margin-bottom:-20vw;\"></div><div><a href=\"https://ssl.gongyi.qq.com/m/weixin/yqj.html?ADTAG=rd#/yqj/detail?id=217239&did=1228013501202111122700001571\"><img src=\"" + path404 + "img/coffeeQR.jpg\" style=\"width:32vw\"></a><br><b style=\"color:white;\">扫码送上一份支持</b></div><b style=\"color:white;\"></b></center><b style=\"color:white;\">"
}, {
    "name": "无障爱",
    id: "accessibility",
    p: 0,
    expires: "2021-12-31",
    bgColor: "#ffffff",
    "pc": "<div style=\"left:50%;width:1600px;margin-left:calc(50% - 800px);\"><div><a href=\"http://www.capa.ac/\"><img alt=\"404！您要访问的页面不见了！\" src=\"" + path404 + "img/123/123pc.png\"></a></div><center style=\"font-size:38px;color:gray\"><a href=\"https://gongyi.qq.com\"><img src=\"" + path404 + "img/gongyi.qq.com.png\" height=\"50px\"></a>&nbsp;<a href=\"http://www.siaa.org.cn/\"><img src=\"" + path404 + "img/123/siaa.png\" height=\"50px\"></a>&nbsp; 123 无障碍联合运营指导单位：中国盲人协会、中国聋人协会</center></div>",
    "mobile": "<a href=\"http://www.capa.ac/\"><img alt=\"404！您要访问的页面走丢了！\" src=\"" + path404 + "img/123/123mobile.png\" style=\"width:100%;\"></a><a href=\"https://gongyi.qq.com\"><img src=\"" + path404 + "img/gongyi.qq.com.png\" height=\"30px\"></a>&nbsp;<a href=\"http://www.siaa.org.cn/\"><img src=\"" + path404 + "img/123/siaa.png\" height=\"30px\"></a><div style=\"color:gray;font-size:1rem\">123 无障碍联合运营指导单位：中国盲人协会、中国聋人协会</div>"
}, {
    "name": "无障碍生活节",
    id: "accessibility2022",
    p: 0,
    expires: "2022-12-12",
    bgColor: "#ffffff",
    "pc": "<div style=\"left:50%;width:1600px;margin-left:calc(50% - 800px);\"><div><a href=\"https://siaa.org.cn\"><img alt=\"404！您要访问的页面不见了！\" src=\"" + path404 + "img/123/202212landsacpe.jpg\"></a></div><center style=\"font-size:38px;color:gray\"><img src=\"https://volunteer.cdn-go.cn//404/0e1dfd7b/img/volunteer.png\" height=\"50px\">&nbsp;<a href=\"http://www.siaa.org.cn/\"><img src=\"" + path404 + "img/123/siaa.png\" height=\"50px\"></a><p>无障碍生活周联合发起方<br>MKTforGOOD<br><br>指导单位<br><nobr>中国助残志愿者协会</nobr>、<nobr>中国助残志愿者协会无障碍环境促进委员会</nobr>、<nobr>中国残疾人事业新闻宣传促进会无障碍文化促进中心</nobr>、<nobr>中国盲人协会</nobr><br><br>支持单位<br>数字适老化及信息无障碍联盟</nobr>、<nobr>中国残疾人信息和无障碍技术研究中心</nobr>、<nobr>深圳市残疾人综合服务中心</nobr>、<nobr>深圳市无障碍孵化空间</nobr>、<nobr>信息无障碍联席会议<br><br>特别支持伙伴<br><nobr>神州租车</nobr>、<nobr>龙湖公益基金会</nobr>、<nobr>讯飞听见</nobr><br><br>合作伙伴<br><nobr>中国电信</nobr>、<nobr>爱德曼国际公关（中国）有限公司</nobr>、<nobr>即时设计</nobr>、<nobr>八位堂</nobr>、<nobr>译迩科技</nobr>、<nobr>声随形动（重庆）文化传媒有限公司</nobr>、<nobr>猫南北喜剧</nobr>、<nobr>OATLY</nobr>、<nobr>LiLi Time</nobr>、<nobr>至正潮菜</nobr>、<nobr>潜愈</nobr>、<nobr>LOOP</nobr>、<nobr>腾讯SSV银发科技</nobr>、<nobr>TEG公益</nobr><br><br>联合传播伙伴<br><nobr>腾讯志愿者</nobr>、<nobr>微软</nobr>、<nobr>荣耀</nobr>、<nobr>中国平安</nobr>、<nobr>OPPO</nobr>、<nobr>vivo</nobr>、<nobr>新浪科技</nobr>、<nobr>新榜</nobr>、<nobr>凰家评测</nobr>、<nobr>雷科技</nobr>、<nobr>电信星播客</nobr>、<nobr>AgeClub</nobr>、<nobr>字由</nobr>、<nobr>UI中国</nobr>、<nobr>优设</nobr>、<nobr>完美世界产业发展研究院</nobr>、<nobr>小洋丁插画</nobr>、<nobr>稀台NFTaas系统</nobr>、<nobr>RELOOK</nobr>、<nobr>统信软件技术有限公司</nobr>、<nobr>IconPark</nobr>、<nobr>声联网</nobr>、<nobr>包小盒</nobr>、<nobr>北师大用户体验研究中心</nobr>、<nobr>聆通科技</nobr>、<nobr>深圳市无障碍城市联合会</nobr>、<nobr>CSDN</nobr>、<nobr>优酷</nobr>、<nobr>Impact Hub Shanghai</nobr>、<nobr>作为科技</nobr>、<nobr>点猫科技</nobr>、<nobr>51CTO</nobr>、<nobr>InfoQ</nobr>、<nobr>深圳市老龄事业发展基金会</nobr>、<nobr>Eva的科技生活</nobr>、<nobr>灵析</nobr>、<nobr>鹏星社工</nobr>、<nobr>美颐享</nobr>、<nobr>微光青年成长计划</nobr>、<nobr>广州市合木残障公益创新中心</nobr>、<nobr>博彦科技</nobr>、<nobr>無予亦屿NOTHINGER</nobr>、<nobr>深圳市慈善事业联合会</nobr>、<nobr>心智互动</nobr>、<nobr>WEable</nobr>、<nobr>全球创业周校园中心</nobr>、<nobr>高德地图</nobr>、<nobr>饿了么</nobr></p></div>",
    "mobile": "<a href=\"https://siaa.org.cn\"><img alt=\"404！您要访问的页面走丢了！\" src=\"" + path404 + "img/123/202212portrait.jpg\" style=\"width:100%;\"></a><img src=\"https://volunteer.cdn-go.cn//404/0e1dfd7b/img/volunteer.png\" height=\"30px\">&nbsp;<a href=\"http://www.siaa.org.cn/\"><img src=\"" + path404 + "img/123/siaa.png\" height=\"30px\"></a><div style=\"color:gray;font-size:1rem\"><br>无障碍生活周联合发起方<br>MKTforGOOD<br><br>指导单位<br><nobr>中国助残志愿者协会</nobr>、<nobr>中国助残志愿者协会无障碍环境促进委员会</nobr>、<nobr>中国残疾人事业新闻宣传促进会无障碍文化促进中心</nobr>、<nobr>中国盲人协会</nobr><br><br>支持单位<br>数字适老化及信息无障碍联盟</nobr>、<nobr>中国残疾人信息和无障碍技术研究中心</nobr>、<nobr>深圳市残疾人综合服务中心</nobr>、<nobr>深圳市无障碍孵化空间</nobr>、<nobr>信息无障碍联席会议<br><br>特别支持伙伴<br><nobr>神州租车</nobr>、<nobr>龙湖公益基金会</nobr>、<nobr>讯飞听见</nobr><br><br>合作伙伴<br><nobr>中国电信</nobr>、<nobr>爱德曼国际公关（中国）有限公司</nobr>、<nobr>即时设计</nobr>、<nobr>八位堂</nobr>、<nobr>译迩科技</nobr>、<nobr>声随形动（重庆）文化传媒有限公司</nobr>、<nobr>猫南北喜剧</nobr>、<nobr>OATLY</nobr>、<nobr>LiLi Time</nobr>、<nobr>至正潮菜</nobr>、<nobr>潜愈</nobr>、<nobr>LOOP</nobr>、<nobr>腾讯SSV银发科技</nobr>、<nobr>TEG公益</nobr><br><br>联合传播伙伴<br><nobr>腾讯志愿者</nobr>、<nobr>微软</nobr>、<nobr>荣耀</nobr>、<nobr>中国平安</nobr>、<nobr>OPPO</nobr>、<nobr>vivo</nobr>、<nobr>新浪科技</nobr>、<nobr>新榜</nobr>、<nobr>凰家评测</nobr>、<nobr>雷科技</nobr>、<nobr>电信星播客</nobr>、<nobr>AgeClub</nobr>、<nobr>字由</nobr>、<nobr>UI中国</nobr>、<nobr>优设</nobr>、<nobr>完美世界产业发展研究院</nobr>、<nobr>小洋丁插画</nobr>、<nobr>稀台NFTaas系统</nobr>、<nobr>RELOOK</nobr>、<nobr>统信软件技术有限公司</nobr>、<nobr>IconPark</nobr>、<nobr>声联网</nobr>、<nobr>包小盒</nobr>、<nobr>北师大用户体验研究中心</nobr>、<nobr>聆通科技</nobr>、<nobr>深圳市无障碍城市联合会</nobr>、<nobr>CSDN</nobr>、<nobr>优酷</nobr>、<nobr>Impact Hub Shanghai</nobr>、<nobr>作为科技</nobr>、<nobr>点猫科技</nobr>、<nobr>51CTO</nobr>、<nobr>InfoQ</nobr>、<nobr>深圳市老龄事业发展基金会</nobr>、<nobr>Eva的科技生活</nobr>、<nobr>灵析</nobr>、<nobr>鹏星社工</nobr>、<nobr>美颐享</nobr>、<nobr>微光青年成长计划</nobr>、<nobr>广州市合木残障公益创新中心</nobr>、<nobr>博彦科技</nobr>、<nobr>無予亦屿NOTHINGER</nobr>、<nobr>深圳市慈善事业联合会</nobr>、<nobr>心智互动</nobr>、<nobr>WEable</nobr>、<nobr>全球创业周校园中心</nobr>、<nobr>高德地图</nobr>、<nobr>饿了么</nobr></div>"
}, {
    "name": "反诈骗游戏",
    id: "antiFraud003",
    p: 0,
    expires: "2021-12-20",
    bgColor: "#0d0e2d",
    "pc": "<img alt=\"404！您要访问的页面走丢了！\" src=\"" + path404 + "img/antiFraud/pc3.png\" style=\"left:50%;width:1600px;margin-left:calc(50% - 800px);\"><div style=\"position:absolute;top:0;width:100%;text-align:center;color:white;font-size:28px;padding:10px\"><div style=\"display:inline-block;width:98vw;max-width:1600px;height:calc(100vh - 100px);max-height:823px;text-align:left;\"><div style=\"font-size:128px;font-weight: 900;\">404</div>您访问的页面可能被坏人拐跑了<br>但是您仍可以学会识别反诈套路<br>成为家人的第一道防线</div><div style=\"display:inline-block;width:98vw;max-width:1600px;text-align:left;margin-top:-200px\"><a href=\"img/antiFraud/QR.png\"><img src=\"" + path404 + "img/antiFraud/QR.png\" alt=\"\" style=\"width:230px;\"></a><div><div style=\"float:right;padding-right:50px\">腾讯志愿者供稿</div><div style=\"float:left\">扫码加入反诈总动员</div></div>",
    "mobile": "<center style=\"height:99vh;font-size:4vw\"><img alt=\"404！您要访问的页面走丢了！\" src=\"" + path404 + "img/antiFraud/mobile3.png\" width=\"100%\"><div style=\"position:absolute;top:0;color:white;text-align: center;width:100%\"><div style=\"font-size:24vw;font-weight: 900;\">404</div>您访问的页面可能被坏人拐跑了<br>但是您仍可以学会识别反诈套路<br>成为家人的第一道防线</div><a href=\"weixin://dl/business/?t=XjYxwCff04a\" style=\"top:125vw;left:34vw;position:absolute;color:white;text-decoration:none;\"><img src=\"" + path404 + "img/antiFraud/QR.png\" style=\"width:32vw\"><div>扫码加入反诈总动员</div></a></center>"
}, {
    "name": "反诈骗游戏",
    id: "antiFraud004",
    p: 0,
    expires: "2021-12-20",
    bgColor: "#d0f7fb",
    "pc": "<img alt=\"404！您要访问的页面走丢了！\" src=\"" + path404 + "img/antiFraud/pc4.png\" style=\"left:50%;width:1600px;margin-left:calc(50% - 800px);\"><div style=\"position:absolute;top:0;width:100%;text-align:center;color:black;font-size:28px;padding:10px\"><div style=\"display:inline-block;width:98vw;max-width:1600px;height:calc(100vh - 100px);max-height:823px;text-align:left;\"><div style=\"font-size:128px;font-weight: 900;\">404</div>您访问的页面可能被坏人拐跑了<br>但是您仍可以学会识别反诈套路<br>成为家人的第一道防线</div><div style=\"display:inline-block;width:98vw;max-width:1600px;text-align:left;margin-top:-200px\"><a href=\"img/antiFraud/QR.png\"><img src=\"" + path404 + "img/antiFraud/QR.png\" alt=\"\" style=\"width:230px;\"></a><div><div style=\"float:right;padding-right:50px\">腾讯志愿者供稿</div><div style=\"float:left\">扫码加入反诈总动员</div></div>",
    "mobile": "<center style=\"height:99vh;font-size:4vw\"><img alt=\"404！您要访问的页面走丢了！\" src=\"" + path404 + "img/antiFraud/mobile4.png\" width=\"100%\"><div style=\"position:absolute;top:0;color:black;text-align: center;width:100%\"><div style=\"font-size:24vw;font-weight: 900;\">404</div>您访问的页面可能被坏人拐跑了<br>但是您仍可以学会识别反诈套路<br>成为家人的第一道防线</div><a href=\"weixin://dl/business/?t=XjYxwCff04a\" style=\"top:130vw;left:34vw;position:absolute;color:black;text-decoration:none;\"><img src=\"" + path404 + "img/antiFraud/QR.png\" style=\"width:32vw\"><div>扫码加入反诈总动员</div></a></center>"
}, {
    "name": "点亮乡村",
    id: "lamp001",
    p: 10,
    expires: "2030-01-01",
    bgColor: "black",
    "pc": "<div style=\"position:relative;left:50%;margin-left:-800px;width:1600px;height:900px;\"><img alt=\"404！您要访问的页面走丢了！\" src=\"" + path404 + "img/lamp/dianliangxiangcun1-1600.jpg\" style=\"left:50%;width:1600px;margin-left:calc(50% - 800px);filter: filter:saturate(200%);\"><div style=\"position:relative;margin-top:-900px;width:100%;text-align:center;color:white;font-size:28px;\"><div style=\"display:inline-block;width:98vw;max-width:1600px;height:calc(100vh - 300px);max-height:610px;\"><div style=\"font-size:128px;font-weight: 900;\">404</div>您访问的页面在黑夜中走丢了<br>不过您还可以和腾讯志愿者一起<br><i><b style=\"font-size:1.2em\">用行动点亮一个新的村庄</b></i></div><div style=\"display:inline-block;width:98vw;max-width:1600px;text-align:left;margin:0px 10px;\"><a href=\"" + path404 + "img/lamp/dianliangxiangcunQR.jpg\"><img src=\"" + path404 + "img/lamp/dianliangxiangcunQR.jpg\" alt=\"点击进入支持页面\" style=\"width:230px;\"></a><ranking style=\"display:inline-block;padding:10px;width:240px;\"></ranking><br>扫码点亮一个村庄<div style=\"float:right;text-align:right;margin-right:1em;margin-top:-4.5em\">图中路灯安装于四川省什邡市马井镇万和村<br>安装时间：2020年4月19日<br>拍摄时间：2020年4月25日<br>（感恩基金会供稿）<a href=\"https://support.qq.com/products/378306\" style=\"color:lightgray;font-size:0.8em;\">我要反馈</a> </div></div></div></div>",
    "mobile": "<center style=\"background-color:black;font-size:4vw;color:#aaaaaa;\"><img alt=\"404！您要访问的页面走丢了！\" src=\"" + path404 + "img/lamp/dianliangxiangcun1-960.jpg\" width=\"100%\" style=\"filter:saturate(200%);\"><div style=\"position:relative;margin-top:-130vw;color:white;text-align: center;width:100%;height:130vw\"><div style=\"font-size:24vw;font-weight: 900;\">404</div>您访问的页面在黑夜中走丢了<br>不过您还可以和腾讯志愿者一起<br><i><b style=\"font-size:1.2em\">用行动点亮一个新的村庄</b></i></div><div style=\"background-image: linear-gradient(to bottom, rgba(0,0,0,0), rgba(0,0,0,1));position:relative;top:-100px;height:100px;margin-bottom:-100px;\"></div><div><a href=\"https://ssl.gongyi.qq.com/m/weixin/yqj.html?gt=xqcyq#/yqj/detail?id=206526&amp;did=1416688801202111022700002734\"><img src=\"" + path404 + "img/lamp/dianliangxiangcunQR.jpg\" style=\"width:32vw\"></a><br><b style=\"color:white;font-size:1.1em\">扫码点亮一个村庄</b><br>图中路灯安装于四川省什邡市马井镇万和村<br>安装时间：2020年4月19日<br>拍摄时间：2020年4月25日<br>（感恩基金会供稿）</div></center>"
}, {
    "name": "点亮乡村2",
    id: "lamp002",
    p: 10,
    expires: "2030-01-01",
    bgColor: "black",
    "pc": "<div style=\"position:relative;left:50%;margin-left:-800px;width:1600px;height:1000px;\"><img alt=\"404！您要访问的页面走丢了！\" src=\"" + path404 + "img/lamp/lamp_pc2.jpg\" style=\"left:50%;width:1600px;margin-left:calc(50% - 800px);filter: filter:saturate(200%);\"><div style=\"position:relative;margin-top:-920px;width:100%;text-align:center;color:white;font-size:28px;\"><div style=\"display:inline-block;width:98vw;max-width:1600px;height:calc(100vh - 300px);max-height:630px;\"><div style=\"font-size:128px;font-weight: 900;\">404</div>您访问的页面在黑夜中走丢了<br>不过您还可以和腾讯志愿者一起<br><i><b style=\"font-size:1.2em\">用行动点亮一个新的村庄</b></i></div><div style=\"display:inline-block;width:98vw;max-width:1600px;text-align:left;margin:0px 10px;\"><a href=\"" + path404 + "img/lamp/dianliangxiangcunQR.jpg\"><img src=\"" + path404 + "img/lamp/dianliangxiangcunQR.jpg\" alt=\"点击进入支持页面\" style=\"width:230px;\"></a><ranking style=\"display:inline-block;padding:10px;width:240px;\"></ranking><br>扫码点亮一个村庄<div style=\"float:right;text-align:right;margin-right:1em;margin-top:-4.5em\">图中路灯安装于陕西省宝鸡市陇县东南镇予村<br>拍摄时间：2021年11月13日<br>（感恩基金会供稿）<a href=\"https://support.qq.com/products/378306\" style=\"color:lightgray;font-size:0.8em;\">我要反馈</a> </div></div></div></div>",
    "mobile": "<center style=\"background-color:black;font-size:4vw;color:#aaaaaa;\"><img alt=\"404！您要访问的页面走丢了！\" src=\"" + path404 + "img/lamp/lamp_mobile2.jpg\" width=\"100%\" style=\"filter:saturate(200%);\"><div style=\"position:relative;margin-top:-130vw;color:white;text-align: center;width:100%;height:130vw\"><div style=\"font-size:24vw;font-weight: 900;\">404</div>您访问的页面在黑夜中走丢了<br>不过您还可以和腾讯志愿者一起<br><i><b style=\"font-size:1.2em\">用行动点亮一个新的村庄</b></i></div><div style=\"background-image: linear-gradient(to bottom, rgba(0,0,0,0), rgba(0,0,0,1));position:relative;top:-100px;height:100px;margin-bottom:-100px;\"></div><div><a href=\"https://ssl.gongyi.qq.com/m/weixin/yqj.html?gt=xqcyq#/yqj/detail?id=206526&amp;did=1416688801202111022700002734\"><img src=\"" + path404 + "img/lamp/dianliangxiangcunQR.jpg\" style=\"width:32vw\"></a><br><b style=\"color:white;font-size:1.1em\">扫码点亮一个村庄</b><br>图中路灯安装于陕西省宝鸡市陇县东南镇予村<br>拍摄时间：2021年11月13日<br>（感恩基金会供稿）</div></center>"
}, {
    "name": "宝贝回家",
    id: "baby001",
    p: 10,
    expires: "2030-01-01",
    "pc": "<div style=\"position:relative;left:50%;margin-left:-800px;width:1600px;height:1024px\"><img alt=\"404！您要访问的页面走丢了！\" src=\"" + path404 + "img/baobeihuijia/baobeihuijia1-1600.jpg\" style=\"width:1600px;height:1024px;margin-left:calc(50% - 800px);filter: grayscale(50%) brightness(50%);\"><div style=\"position:relative;margin-top:-1024px;width:100%;text-align:center;color:white;font-size:28px;padding:10px\"><div style=\"display:inline-block;width:99vw;max-width:1600px;height:calc(100vh - 110px);max-height:900px;text-align:left;\"><div style=\"font-size:128px;font-weight: 900;\">404</div>您访问的页面和服务器失散了<br>但是您仍可以为另一些失散者<br>做一点事</div><div style=\"display:inline-block;width:98vw;max-width:1600px;text-align:left;margin-top:-200px\"><a href=\"img/baobeihuijia/baobeihuijiaQR.jpg\"><img src=\"" + path404 + "img/baobeihuijia/baobeihuijiaQR.jpg\" alt=\"点击进入支持页面\" style=\"width:230px;\"></a><ranking style=\"display:inline-block;padding:10px;width:240px;\"></ranking><div><div style=\"float:right\">2021年十月，周士云与失散63年的家人团聚（宝贝回家供图）<a href=\"https://support.qq.com/products/378306\" style=\"color:lightgray;font-size:0.8em;\">我要反馈</a> &nbsp; </div><div style=\"float:left\">扫码帮助宝贝回家</div></div></div></div></div>",
    "mobile": "<center style=\"color:#aaaaaa;height:143vw;font-size:4vw\"><img alt=\"404！您要访问的页面走丢了！\" src=\"" + path404 + "img/baobeihuijia/baobeihuijia1-960.jpg\" width=100% style=\"filter: grayscale(50%) brightness(50%);\"><div style=\"position:relative;margin-top:-140vw;color:white;text-align: center;width:100%\"><div style=\"font-size:24vw;font-weight: 900;\">404</div>您访问的页面和服务器失散了<br>但是您仍可以为另一些失散者<br>做一点事</div><a href=\"https://ssl.gongyi.qq.com/m/weixin/yqj.html?gt=xqcyq#/yqj/detail?id=204701&did=1218675501202111054300002752\" style=\"width:100%;text-align:center;top:35vw;position:relative;color:white;text-decoration:none;\"><img src=\"" + path404 + "img/baobeihuijia/baobeihuijiaQR.jpg\" style=\"width:32vw\"><div>扫码帮助宝贝回家</div></a><div style=\"position:relative;margin-top:37vw\">2021年十月，周士云与失散63年的家人团聚<br>（宝贝回家供图）</div></center>"
}, {
    "name": "宝贝回家2",
    id: "baby002",
    p: 10,
    expires: "2030-01-01",
    "pc": "<div style=\"position:relative;left:50%;margin-left:-800px;width:1600px;height:1200px;\"><img alt=\"404！您要访问的页面走丢了！\" src=\"" + path404 + "img/baobeihuijia/baobeihuijia2-1600.jpg\" style=\"width:1600px;height:1200px;margin-left:calc(50% - 800px);filter: grayscale(50%) brightness(50%);\"><div style=\"position:relative;margin-top:-1200px;width:100%;text-align:center;color:white;font-size:28px;padding:10px\"><div style=\"display:inline-block;width:99vw;max-width:1600px;height:calc(100vh - 150px);max-height:1100px;text-align:left;\"><div style=\"font-size:128px;font-weight: 900;\">404</div>您访问的页面和服务器失散了<br>但是您仍可以为另一些失散者<br>做一点事</div><div style=\"display:inline-block;width:98vw;max-width:1600px;text-align:left;margin-top:-200px\"><a href=\"img/baobeihuijia/baobeihuijiaQR.jpg\"><img src=\"" + path404 + "img/baobeihuijia/baobeihuijiaQR.jpg\" alt=\"点击进入支持页面\" style=\"width:230px;\"></a><ranking style=\"display:inline-block;padding:10px;width:240px;\"></ranking><div><div style=\"float:right\">2021年十月，王建留与失散62年的家人团聚（宝贝回家供图）<a href=\"https://support.qq.com/products/378306\" style=\"color:lightgray;font-size:0.8em;\">我要反馈</a> &nbsp; </div><div style=\"float:left\">扫码帮助宝贝回家</div></div></div></div></div>",
    "mobile": "<center style=\"color:#aaaaaa;height:141vw;font-size:4vw\"><img alt=\"404！您要访问的页面走丢了！\" src=\"" + path404 + "img/baobeihuijia/baobeihuijia2-960.jpg\" width=100% style=\"filter: grayscale(50%) brightness(50%);\"><div style=\"position:relative;margin-top:-140vw;color:white;text-align: center;width:100%\"><div style=\"font-size:24vw;font-weight: 900;\">404</div>您访问的页面和服务器失散了<br>但是您仍可以为另一些失散者<br>做一点事</div><a href=\"https://ssl.gongyi.qq.com/m/weixin/yqj.html?gt=xqcyq#/yqj/detail?id=204701&did=1218675501202111054300002752\" style=\"top:25vw;text-align:center;position:relative;color:white;text-decoration:none;\"><img src=\"" + path404 + "img/baobeihuijia/baobeihuijiaQR.jpg\" style=\"width:32vw\"><div>扫码帮助宝贝回家</div></a><div style=\"position:relative;margin-top:34vw\">2021年十月，王建留与失散62年的家人团聚<br>（宝贝回家供图）</div></center>"
}, {
    "name": "免费午餐",
    id: "freelunch01",
    p: 20,
    expires: "2030-01-01",
    "pc": "<div style=\"left:50%;width:1600px;height:900px;margin-left:calc(50% - 800px);border:30px coral solid;text-align:center;\"><img src=\"" + path404 + "img/freelunch1600.jpg\" width=\"860\" style=\"margin-top:50px;\"><div style=\"display:inline-block;width:1500px;height:300px;margin-top:-260px;color:rgb(118,179,234)\"><i style=\"float:left;text-align:left;font-size:32px\"><div style=\"font-weight: 900;font-size:150px;height:180px\">404</div>您访问的页面<br>已经饿晕在路上<br>不过您还可以和腾讯志愿者一起<br>为孩子们送上一份午餐</i><span style=\"float:right\"><div style=\"position:relative;font-size:40px;transform: rotate(45deg);left:0px;z-index:-1;\">❤️</div><span><img src=\"" + path404 + "img/freeLungchQR.png\" width=\"250px\"><div style=\"font-size:32px;\"><i style=\"float:left;margin:0px 0px 0px 40px\">扫 码 支 持</i></div></span></span></div><div style=\"position:absolute;top:975px;font-size:20px;color:grey\">图片由免费午餐提供并授权使用</div></div>",
    "mobile": "<center style=\"color:rgb(118,179,234);border:15px solid coral;width:99wv\"><i><b><br><div style=\"font-size:14vw;\">404</div><br><div style=\"font-size:4.5vw;\">您访问的页面<br>已经饿晕在路上<br>不过您还可以和腾讯志愿者一起<br>为孩子们送上一份午餐<br></div></b></i><br><img src=\"" + path404 + "img/freelunch1600.jpg\" width=\"80%\"><div style=\"position:relative;font-size:10vw;transform: rotate(45deg);left:28vw\">❤️</div><a href=\"https://ssl.gongyi.qq.com/m/weixin/yqj.html?et=yqjqp#/yqj/detail?id=415&amp;did=1589709871202204181800001717\"><img src=\"" + path404 + "img/freeLungchQR.png\" width=\"50%\"></a><br><i style=\"font-size:5vw\">扫码支持</i></center><font color=\"grey\">图片由免费午餐提供并授权使用</font>"
}, {
    "name": "一校一梦想",
    id: "dream4school",
    p: 600,
    expires: "2030-01-01",
    "pc": "<div style=\"position:relative;left:50%;margin-left:-800px;width:1600px;height:1000px;\"><img alt=\"404！您要访问的页面走丢了！\" src=\"" + path404 + "img/dream4school.jpg\" style=\"left:50%;width:1600px;margin-left:calc(50% - 800px);filter: brightness(75%);\"><div style=\"position:relative;margin-top:-1200px;width:100%;text-align:center;color:white;font-size:28px;\"><div style=\"display:inline-block;width:98vw;max-width:1600px;height:calc(100vh - 250px);max-height:750px;\"><div style=\"font-size:128px;font-weight: 800;\">404</div>您访问的页面走丢在寻找梦想的路上了<br>不过您还可以和腾讯志愿者一起<br><i><b style=\"font-size:1.2em\">为孩子们点亮一个梦想</b></i></div><div style=\"display:inline-block;width:98vw;max-width:1600px;text-align:left;margin:0px 10px;font-size:0.75em\"><a href=\"" + path404 + "img/dream4schoolQR.png\"><img src=\"" + path404 + "img/dream4schoolQR.png\" alt=\"点击进入支持页面\" style=\"width:160px;\"></a><br>扫码点亮一个梦想<div style=\"float:right;text-align:right;margin-right:1em;margin-top:-4.5em\">照片拍摄于湖南省岳阳市平江县三市镇新村完小<br>拍摄时间：2023年7月11日<br>（感恩基金会供稿）<a href=\"https://support.qq.com/products/378306\" style=\"color:lightgray;font-size:0.8em;\">我要反馈</a> </div></div></div></div>",
    "mobile": "<center style=\"background-color:black;font-size:4vw;color:#aaaaaa;\"><img alt=\"404！您要访问的页面走丢了！\" src=\"" + path404 + "img/dream4School_mobile2.jpg\" width=\"100%\" ></a><div style=\"position:relative;margin-top:-190vw;color:white;text-align: center;width:100%;height:190vw\"><div style=\"font-size:24vw;font-weight: 900;\">404</div>您访问的页面走丢在寻找梦想的路上了<br>不过您还可以和腾讯志愿者一起<i><b style=\"font-size:1.2em\">为孩子们点亮一个梦想</b></i></div><div style=\"margin-top:-32vw\"><a style=\"position:relative; width:192px;height:192px;top:-17vw;z-index:999;display:block;\" href=\"weixin://dl/business/?appid=wxfdcee92a299bcaf1&path=pages/detail/main&query=spmet%3D109.9896.9897%26pid%3D3014664&env_version=release\"><img src=\"" + path404 + "img/dream4schoolQR.png\" style=\"width:30vw;visibility: hidden;\"></a><br><b style=\"color:white;font-size:1.1em\">扫码点亮一个梦想</b><br>照片拍摄于湖南省岳阳市平江县三市镇新村完小<br>拍摄时间：2023年7月11日<br>（感恩基金会供稿）</div></center>"
}
]

if (document.currentScript && typeof document.currentScript.callback == 'function') {
    document.currentScript.callback(data)
}
